# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18656f6dd3a32c111edde0152889f31c6d49cd7a2909b01b8339f1cef525aa3bd0f830cb21322585b6d3839ea989f406901f19ea2fbdbb7f514a0412bd3fdb8a

test:
  secret_key_base: 934bdb4a99f5012db7aba4d31b4e0e98174165514315f23a81da34baee534a2372eed32114bf7539eb7861b0b20f7d02a8d679643519d95fa1ddf214a3bfcc33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
